# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='retry',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='top',
            name='created_date',
        ),
        migrations.AddField(
            model_name='queue',
            name='number',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retry',
            name='number',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='top',
            name='number',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
